rss_sources:
  - name: "TASS"
    url: "https://www.bing.com/news/search?q=site:tass.com&format=rss"
  - name: "BBC"
    url: "https://feeds.bbci.co.uk/news/world/rss.xml"
  - name: "CNBC"
    url: "https://www.cnbc.com/id/100727362/device/rss/rss.html"
llm:
  api_key: "" # ds官方
  base_url: "https://api.deepseek.com"
  model: "deepseek-v4-flash"

feishu:
  app_id: ""
  app_secret: ""
  app_token: ""
  table_id: ""
